add tests to the registration form
SharnikovaElena/Sharelane pull request #1
Opened 2021-11-18 13:27 UTC by SharnikovaElena

2021-11-18 14:04 UTC, mikola-2 requested changes

2021-11-18 14:04 UTC, mikola-2 commented on src/test/java/SingUpTest.java
> +    WebDriver driver;
Блок с 78 по 91 строки перемещай в самый верх класса.

2021-11-18 14:04 UTC, mikola-2 commented on src/test/java/SingUpTest.java
> +    @BeforeTest
Before и After методы обычно указываются вверху класса. Чтобы было понятно, что они применяются ко всем тестам.

2021-11-18 14:04 UTC, mikola-2 commented on src/test/java/SingUpTest.java
>          WebDriver driver = new ChromeDriver();
Проверить сейчас не могу, но мне кажется, что у тебя в старых тестах будут два раза вызываться методы driver.get() в разных браузерах. launchBrowser() метод будет вызываться и тут тоже. Нужно немного подрефакторить старые и новые методы, чтобы они работали с одним браузером.

2021-11-18 14:13 UTC, SharnikovaElena commented on src/test/java/SingUpTest.java
>          WebDriver driver = new ChromeDriver();
у меня в методе @BeforTest вызывается страница с уже пройденным zip code, т.е. открывается сразу форма регистрации. А первые тесты (старые) как раз на ввод Zip code. Если я в BeforTest пропишу ссылку на страничку с zip code, получится, что мне нужно будет в каждом тесте на проверку SinUp описывать шаг введения валидного пароля для zip code. Что делать?

2021-11-18 14:13 UTC, SharnikovaElena commented on src/test/java/SingUpTest.java
> +    @BeforeTest
здесь поправила

2021-11-19 06:16 UTC, SharnikovaElena commented
add tests to the SingUp form

2021-11-19 06:17 UTC, merged

2021-11-19 07:52 UTC, mikola-2 commented on src/test/java/SingUpTest.java
>          WebDriver driver = new ChromeDriver();
В старых методах оставляй driver.get("https://www.sharelane.com/cgi-bin/register.py");
А в новых вставляй driver.get("https://www.sharelane.com/cgi-bin/register.py?page=1&zip_code=12345");